script: bash ./publish.sh
language: node_js
node_js:
- 6.1.0
cache:
  directories:
  - node_modules
branches:
  only:
  - /^release\/.*$/
env:
  global:
    secure: gusOr4O8yebAaGBV8eEvTLqjEmepP8sBE6W1Sc0Ioc8SkRvshIyo6L6dv0LskaSKXNLQsdDw8cyPh+hds6JIjZ6Bu3EctIXmIfn7QeR79BVW8pKF2CaVG4i6Z54asVEIp7vmHHTNtXsHwF5Bg7fOoajxJUFznOYDku5Rv0og+2PDWoxCKkZiO01D3XMrn4ImBO/Z+w8R0J19QCNC1r09cuDfbT17C2d1I55PtonAY+3+fG6vlHrvUVdIU11IuyrVWg67wOGDE3vO0scXVxzoApNLo1Gujcag2oKwixudM6YZWHFyFudTf2ZCrEXyAXnnfkT9RSRDnVmDSz61lTvAlIfBJ7gvGMeRd/TuA3tUCJaSIzjEsR2Wt7Jij0YUP2ECIMQFwC6orVh41YuPU46PynF0Xo3BEptK0kL/2yqnZ9B4LtMzmfyDAu1347IW2D/QPWHP5WdSI+7+vaOkAuOav9gIkXHQCbO5DZAIeH6w5oUYmubmIysEd++UU9cFUtf3KPt/QIt6Lyx8jz/ZSKGDVDEFw0a4j2+lgEEefy88oXdpkSibX51hEbFt43gEiSTo5Ta2zBgwA8Olh/rkuPWftrJRvtmfpILEIwukO1SZTJuubno8CdW1UCit46bxj1wuAJ5mBqxmlayC1h8Bdg6lMMPS6smqAM4g4vx96uARpXQ=
