language: node_js
node_js:
  - 10.15
cache:
  directories:
    - node_modules
branches:
  only:
    - /^release\/.*$/
script:
  - npm run build
before_deploy:
  - './publish.sh'
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  target_branch: master
  on:
    all_branches: true
    condition: ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} =~ ^release\/.*$
env:
  global:
    secure: 'lF7EO6ZGIJFQnbMg1E+/Y4DSbH8TTjvLngVGukn+dvHKskw1tHN+blfGqY61VzIwT7IaZwf84eQ+4197u3TUDwLi2d12x0qdcvds2f+fO4/f7xtOBdzrctpN2/2xse62yCnphJGiApvxUKv2ooT4jT5IGoBzSR90G8XxECKwc5FNdho7vaoRYUP0FulX310y+JHzvoSNRFORjhOebmF/r7hfHD+4XueBQHNL16Sn0C6AqxOHvYbuvsweKUvn+BIvgzZl32lMIQoLbHiR+F+HvbdN40FxERPHN9Mr3SQ8t2EyNvfb3cRQeFyxS6YmRxlQHI/XS7afwpzUJZJ5oNBKeBVUSac9HjSG8TYyyCOwwcWHVUc5HegfqsIWS5RTFy8SE+hDRcWYx8r91vYNIQNOdvdxcoqb9hyOFQUjebwc2LyybV4MJ6sZC3LG47asVo+3ZTrCSfTPxhzInp/EjEg9WeQ85vSdR3Xz8C1S+RuB8B9WdEf85L9tdsCDTMxkN3Ko4nbnCn6DCAAQ7f7XUKudLZqmvNLH1eSNC1RX7yw3ssZyA+qgk5sCG4bziWw2/AKF+PnE6in81kcMPfSVSUpz1ubHw54VedjbDPw0yZUsYW4szuHNmJ3xbTe+hUixlTrhU6lYBEeuH9gcJ7m1XF5X/bQwxHnUmRodHyOeEFu01Gk='
