export const
    APP_RELOAD = 'APP_RELOAD',
    EDITOR_TAB_SELECT = 'EDITOR_TAB_SELECT',
    EDITOR_TAB_CLOSE = 'EDITOR_TAB_CLOSE',
    EDITOR_TAB_CHANGE_POSITION = 'EDITOR_TAB_CHANGE_POSITION',
    EDITOR_FILE_OPEN = 'EDITOR_FILE_OPEN',
    EDITOR_FILE_TREE_ELEM_SELECT = 'EDITOR_FILE_TREE_ELEM_SELECT',
    EDITOR_FILE_TREE_TOGGLE_DIR_COLLAPSE = 'EDITOR_FILE_TREE_TOGGLE_DIR_COLLAPSE'
    ;
