export const
    APP_RELOAD = 'APP_RELOAD',
    EDITOR_TAB_SELECT = 'EDITOR_TAB_SELECT',
    EDITOR_TAB_CLOSE = 'EDITOR_TAB_CLOSE',
    EDITOR_TAB_CHANGE_POSITION = 'EDITOR_TAB_CHANGE_POSITION'
    ;
